data_path: data/adult.csv
target: income
positive_label: ">50K"
protected_attributes:
  gender: gender
  race: race
privileged_groups:
  gender: Male
  race: White
test_size: 0.2
random_state: 42
fairness_thresholds:
  dp_gap_max: 0.1
  eo_gap_max: 0.1
  di_min_ratio: 0.8
